version: "3.9"
services:
  authservice:
    container_name: authservice
    image: ngomalalibo/authservice
    mem_limit: 1024m
    mem_reservation: 128M
    ports:
      - "8901:8901"
    environment:
      MONGODB_DATABASE_STOCKS_ATLAS: ${MONGODB_DATABASE_STOCKS_ATLAS}
      ENCRYPT_KEY: ${ENCRYPT_KEY}
      EUREKA_URI: "http://18.156.118.22:8761/eureka/"
      AUTH_URI: "http://3.121.40.225:8901/user"
      CONF_URI: "http://3.121.40.225:8888"
      DATABASE_URI: ${DATABASE_URI}
      ZIPKIN_URI: "http://18.156.118.22:9411"
      ZUUL_URI: "http://18.184.55.40:5555"
  confserver:
    container_name: confserver
    image: ngomalalibo/confserver
    mem_limit: 1024m
    mem_reservation: 128M
    ports:
      - "8888:8888"
    environment:
      ENCRYPT_KEY: ${ENCRYPT_KEY}
      CONF_URI: "http://3.121.40.225:8888"
