version: "3.9"
services:
  authservice:
    container_name: authservice
    image: ngomalalibo/authservice
    mem_limit: 1024m
    mem_reservation: 128M
    ports:
      - "8901:8901"
    environment:
      MONGODB_DATABASE_STOCKS_ATLAS: "mongodb+srv://stocks:stocks@mflix-lfo1z.mongodb.net/test?retryWrites=true&w=majority"
      ENCRYPT_KEY: "IMSYMMETRIC"
      EUREKA_URI: "http://18.156.118.22:8761/eureka/"
      AUTH_URI: "http://3.121.40.225:8901/user"
      CONF_URI: "http://3.121.40.225:8888"
      DATABASE_URI: "mongodb+srv://stocks:stocks@mflix-lfo1z.mongodb.net/test?retryWrites=true&w=majority"
      ZIPKIN_URI: "http://18.156.118.22:9411"
      ZUUL_URI: "http://18.184.55.40:5555"
  confserver:
    container_name: confserver
    image: ngomalalibo/confserver
    mem_limit: 1024m
    mem_reservation: 128M
    ports:
      - "8888:8888"
    environment:
      ENCRYPT_KEY: "IMSYMMETRIC"
      CONF_URI: "http://3.121.40.225:8888"
